<div id="voltar" class="col-md-1 col-md-push-6 text-center" style="color: #D89D33; cursor: pointer"><i class="fa fa-arrow-circle-left fa-2x"></i></div>

<?php 
if(isset($this->coluna)): 
    $coluna = $this->coluna;
    echo $this->partial('exibe_coluna',['coluna'=>$coluna]);
?>
<?php 
else:
    
?>

exibir colunas da categoria

<?php endif; ?>


<script>
    $(function (){
        $(".navbar .icone-categoria img[data-ctg!='pensando_cabeca']").hide();
        $(".navbar .icone-categoria img[data-ctg='pensando_cabeca']")
                .attr('src','/img/id-visual/mente-circle.svg')
                .parent()
                .removeClass('col-md-9')
                .addClass('col-md-push-8 col-md-11')
                .append('<div style="color: #FDFDFE; font-size:1.2em">Pensando com a Cabeça<div>');
        $('#container-topo').css({'border-bottom':'1px solid #D89D33'})
        
        $('#voltar').css('top', $(window).height()/2 ).click(function (){window.location='/'})
    })
</script>