
<?php
$coluna = $this->coluna;
$categoria = $coluna['ctg_apelido'];

$cor = '#D89D33';
if($categoria == 'pensando-coracao'){
    $cor = '#C270AD';
} else if($categoria == 'pensando-biblia') {
    $cor = '#2D84C6';
}
?>

<style>
    
    .layout-logo-principal {
        /*text-align: right;*/
    }
    
/*    .navbar .icone-categoria img:not([data-ctg='<?=$coluna['ctg_apelido']?>']) {
        display: none
    }*/
    
    .layout-icone-logar{
        margin: 2%
    }
    
    #container-topo{
        border-bottom:1px solid #D89D33;
    }
    
    #coluna{
        background: #EEE;
        margin-top: 20px;
        margin-bottom: 20px;
        padding: 20px;
            
    }
    
    #col_titulo{
        font-size: 2.7em;
    }
    
    #col_citacao p{
        margin: 0;
    }
    
    #col_texto{
        font-size: 1.3em;
    }
    #col_texto:first-letter{
        font-size: 4em;
    }
    #col_texto:first-letter{
        line-height: 0
    }
    
    .coluna-voltar{
        color: <?=$cor?>;
    }
</style>

<div id="coluna" class="col-xs-29 ">
    <div class="col-xs-1 text-center coluna-voltar"><i class="fa fa-arrow-circle-left fa-2x"></i></a></div>
    <div id="col_titulo" class="col-md-30 text-center"> <?= $coluna['col_titulo'] ?> </div>
    <blockquote id="col_citacao" class="text-right">
        <footer>Por <cite><?= $coluna['usr_nome'].' '.$coluna['usr_sobrenome'] ?></cite></footer>
        <footer>Em <?= $coluna['col_data_postagem'] ?></footer>
    </blockquote>
    <?php if( !empty($coluna['col_end_imagem'])):?>
<!--    <div class="col-md-10 float-right">
        <img style="width: 100%;" src="<?= $this->basePath().'/img/colunas/'.$coluna['col_end_imagem'].'.jpeg'?>" />
    </div>-->
    <?php endif;?>
    <div id="col_texto" class="text-justify "> <?= nl2br($coluna['col_texto']) ?> </div>
</div>

<script>

    $(".layout-logo-principal").removeClass('col-xs-20 col-xs-push-4').addClass('col-xs-10');
    
    $(".navbar .icone-categoria img:not([data-ctg='<?=$coluna['ctg_apelido']?>'])").parent().remove()
            
    $(".navbar .icone-categoria img[data-ctg='<?=$coluna['ctg_apelido']?>']")
        .parent()
        .removeClass('col-xs-5 col-md-9')
        .addClass('col-md-pull-1 col-xs-12 col-md-20')
        .append('<div style="color: #FDFDFE; font-size:1.2em"><?=$coluna['ctg_nome']?><div>');

    $('.coluna-voltar').click(function (){ window.location='/';})
</script>