
<?php
$this->plugin('basePath')->setBasePath('/public/');


$coluna = $this->coluna;
$categoria = $coluna['ctg_apelido'];
$filhas = $coluna['filhas'];
$titulo_alterado = $coluna['col_titulo'];
if($coluna['col_titulo'] == $coluna['ser_nome']){
    $titulo_alterado .= "<i> - Introdução </i>";
} else if(strlen($coluna['ser_nome'])) {
    $titulo_alterado .= "<i> - Parte {$this->p()->arabic2roman($coluna['ser_ordem'])} </i>";
}

$imagem_face = $coluna['col_end_imagem'];
if (is_null($imagem_face) || empty(trim($imagem_face))) {
    $imagem_face = 'http://ospensadores.com/public/img/id-visual/pensadores.png';
}

$this->headMeta()
                ->setProperty("og:url", "http://ospensadores.com/coluna/{$coluna['ctg_apelido']}/{$coluna['col_id']}")
                ->setProperty("og:title", "$titulo_alterado")
                ->setProperty("og:description", "{$coluna['col_resumo']}")
                ->setProperty("og:image", $imagem_face )
                ->setProperty("og:image:width", getimagesize($imagem_face)[0])
                ->setProperty("og:image:height", getimagesize($imagem_face)[1])
                ->setProperty("og:image:type", "png")
                ->setProperty("og:type", "article")

                ->setProperty("og:author", $coluna['usr_nome'].' '.$coluna['usr_sobrenome'])
                ->setProperty("og:published_time", "{$coluna['col_data_postagem']}");

                    

$cor = '#D89D33';
if($categoria == 'pensando-coracao'){
    $cor = '#C270AD';
} else if($categoria == 'pensando-biblia') {
    $cor = '#2D84C6';
}
?>

<style>
    
    .layout-logo-principal {
        /*text-align: right;*/
    }
    
    .layout-icone-logar{
        margin: 2%
    }
    
    #container-topo{
        border-bottom:1px solid #D89D33;
    }
    
    #coluna{
        background: #EEE;
        margin-top: 20px;
        margin-bottom: 20px;
        padding: 20px 0;    
    }
    
    #col_titulo{
        font-size: 2.7em;
    }
    
    #col_citacao p{
        margin: 0;
    }
    
    #col_texto{
        font-size: 1.3em;
        padding: 20px;
        margin-top: 70px;
    }
    #col_texto:first-letter{
        font-size: 4em;
    }
    #col_texto:first-letter{
        line-height: 0
    }
    #col_texto p {
        text-indent: 25px
    }
    
    .coluna-voltar{
        color: <?=$cor?>;
    }
    
    #serie_nome{
        font-size: 1.2em;
        margin-left: 20px
    }
        
    
    #barra_series{ 
        margin-top: 18px;
        text-align: center;
    }
    
    .bloco_serie{
        background: rgba(238, 238, 238, 0.49);
        padding: 7px;
        margin-bottom: 10px;
        font-size: 1.3em;
    }
    
    .series_link{
        
    }
    
    a.series_link:link, a.series_link:visited {
	text-decoration: none;
        color: #333
        
    }
    a.series_link:hover {
        text-decoration: underline; 
        color: #000
    }
    a.series_link:active {
        text-decoration: none
    }
    
</style>

<div id="coluna" class="col-xs-30 col-md-18 col-md-push-4">
    <div class="col-xs-1 text-center coluna-voltar"><i class="fa fa-arrow-circle-left fa-2x"></i></a></div>
    <?php if(strlen($coluna['ser_nome'])):?>
    <div id="serie_nome" class="col-md-30"><?="Série: <i>{$coluna['ser_nome']}</i>"?></div>
    <?php endif;?>
    <div id="col_titulo" class="col-md-30 text-center"> <?= $titulo_alterado ?> </div>
    <blockquote id="col_citacao" class="text-right">
        <footer>Por <cite><?= $coluna['usr_nome'].' '.$coluna['usr_sobrenome'] ?></cite></footer>
        <footer><cite><a href="https://<?= $coluna['usr_pagina_web'] ?>"><?= $coluna['usr_pagina_web'] ?></a></cite></footer>
        <footer>Em <?= $coluna['col_data_postagem'] ?></footer>
    </blockquote>
    <?php if( !empty($coluna['col_end_imagem'])):?>
<!--    <div class="col-md-10 float-right">
        <img style="width: 100%;" src="<?= $this->basePath().'/img/colunas/'.$coluna['col_end_imagem'].'.jpeg'?>" />
    </div>-->
    <?php endif;?>
    <div id="col_texto" class="text-justify "> <?= $coluna['col_texto']; ?> </div>
</div>

<?php if(sizeof($filhas)):?>
<span id="barra_series" class="col-md-7 col-md-push-4">
    <span  style="color: #EEE; font-size: 1.5em;">Acompanhe esta série</span>
    
    <?php foreach ($filhas as $filha) :?>
    <div class="col-xs-30 bloco_serie text-left">
        <?php
            if($filha['col_titulo'] == $coluna['col_titulo']){
                echo  '<span>'.$filha["col_titulo"].' (lendo agora)</span>';
            } else {
                echo  '<a class="series_link" href="'."/coluna/{$filha['ctg_apelido']}/{$filha['col_id']}".'">'.$filha["col_titulo"].'</a>';
            }
        ?>
        
    </div>
    <?php endforeach; ?>
</span>
<?php endif; ?>
<script>

    $(".layout-logo-principal").removeClass('col-xs-20 col-xs-push-4').addClass('col-xs-10');
    
    $(".navbar .icone-categoria img:not([data-ctg='<?=$coluna['ctg_apelido']?>'])").parent().remove()
            
    $(".navbar .icone-categoria img[data-ctg='<?=$coluna['ctg_apelido']?>']")
        .parent()
        .removeClass('col-xs-5 col-md-9')
        .addClass('col-md-pull-1 col-xs-12 col-md-20')
        .append('<div style="color: #FDFDFE; font-size:1.2em"><?=$coluna['ctg_nome']?><div>');

    $('.coluna-voltar').click(function (){ window.location='/';})
    
    $('.bloco_serie').hover(function (){
        $(this).css({ background: 'rgba(238, 238, 238, 1)', color: '#000'});
    }, function(){
        $(this).css({ background: 'rgba(238, 238, 238, 0.49)', color: '#000'});
    });
    
    
</script>