<?php 
$coluna = $this->coluna;
$tipo_bloco = 'paisagem';
$categoria = $coluna['ctg_apelido'];

$cor = '#D89D33';
if($categoria == 'pensando-coracao'){
    $cor = '#C270AD';
} else if($categoria == 'pensando-biblia') {
    $cor = '#2D84C6';
}
?>
<style>
    div .paisagem img{
        max-width: 430px;
        margin-top: 2px;
    }
    div .retrato img{
        max-width: 223px;
    }
</style>

<?php if($tipo_bloco == 'paisagem'):?>
<li>
    <div class="text-center no-padding" style="height: 353px">
        <div class="col-md-30 icone-categoria text-center"><img src="<?=$this->basePath() . '/img/id-visual/mente-circle.svg'?>" /></div>
        <img style="max-height: 228px; margin-top: 2px" src="<?= $coluna['col_end_imagem'] ?>" />
        <div class="col-md-30">
            <div class="text-justify clear bloco-titulo col-md-20" ><?= $coluna['col_titulo'] ?></div>
            <div id="col_dest_detalhes" class="text-right" >
                <div><i>'Por Autor da Coluna'</i></div>
                <div><i>Há 5 min.</i></div>
            </div>
            <div class="text-right">
                <a href="/coluna/<?=$coluna['ctg_apelido']?>/<?=$coluna['col_id']?>">
                    <div class="btn btn-warning" style="min-width: 100px; font-size: 16px; background-color: <?=$cor?>; border-color: <?=$cor?>">Saiba mais...</div>
                </a>
            </div>

        </div>
    </div>
</li>


<?php elseif($tipo_bloco == 'retrato'):?>

<li>
    <div class="text-center no-padding" style="height: 353px">
        <div class="col-md-15" style="height: 354px; background: black; overflow: hidden">
            <div id="col_dest_end_imagem" class="retrato" style="padding: 0;"><img src="<?=$this->basePath() . '/img/id-visual/mente-circle.svg'?>" /></div>
        </div>
        <div class="col-md-15">
            <div class="col-md-30 text-center icone-categoria"><img src="<?= $coluna['col_end_imagem'] ?>" /></div>
            <div class="text-justify bloco-titulo" style="padding-left: 8px"><?= $coluna['col_titulo'] ?></div>
            <div id="col_dest_detalhes" class="clear text-right">
                <div><i>Por 'Autor da Coluna'</i></div>
                <div><i>Há 5 min.</i></div>
            </div>
            <div class="text-right">
                <div class="btn btn-warning" style="min-width: 100px; font-size: 16px; background-color: <?=$cor?>; border-color: <?=$cor?>">Saiba mais...</div>
            </div>
        </div>
    </div>
</li>

<?php endif; ?>  


