<?php 
$coluna = $this->coluna;
$categoria = $coluna['ctg_apelido'];

$cor = '#D89D33';
$icone = $this->basePath() . '/img/id-visual/mente-circle.svg';
if($categoria == 'pensando-coracao'){
    $cor = '#C270AD';
    $icone = $this->basePath() . '/img/id-visual/coracao-circle.svg';
} else if($categoria == 'pensando-biblia') {
    $cor = '#2D84C6';
    $icone = $this->basePath() . '/img/id-visual/biblia-circle.svg';
}
?>
<style>
    div .paisagem img{
        max-width: 430px;
        margin-top: 2px;
    }
    div .retrato img{
        max-width: 223px;
    }
</style>

<?php if($coluna['orient_imagem'] == 'paisagem'):?>
<li>
    <div class="text-center no-padding" style="height: 353px">
        <div class="col-md-30 icone-categoria text-center"><img src="<?=$icone?>" /></div>
        <div class="col-md-30" style="background-color: black; padding: 0">
            <img style="max-height: 228px; width: 100%" src="<?= $coluna['col_end_imagem'] ?>" />
        </div>
        <div class="col-md-30">
            <div class="text-justify clear bloco-titulo col-md-20" ><?= $coluna['col_titulo'] ?></div>
            <div id="col_dest_detalhes" class="text-right" >
                <div>Por <i><?= $coluna['usr_nome'].' '.$coluna['usr_sobrenome'] ?></i></div>
                <div>Em <i><?= $coluna['col_data_postagem'] ?></i></div>
            </div>
            <div class="text-right">
                <a href="/coluna/<?=$coluna['ctg_apelido']?>/<?=$coluna['col_id']?>" target="_blank">
                    <div class="btn btn-warning" style="min-width: 100px; font-size: 16px; background-color: <?=$cor?>; border-color: <?=$cor?>">Saiba mais...</div>
                </a>
            </div>

        </div>
    </div>
</li>


<?php else:?>

<li>
    <div class="text-center no-padding" style="height: 353px">
        <div class="col-md-15" style="height: 354px; background: black; overflow: hidden; padding: 0">
            <div class="text-center"><img style="max-width: 100%" src="<?= $coluna['col_end_imagem'] ?>" /></div>
        </div>
        <div class="col-md-15">
            <div id="col_dest_end_imagem" class="retrato" style="margin-top: 2px; padding: 0;"><img src="<?=$icone?>" /></div>
            <div class="text-justify bloco-titulo" style="padding-left: 8px"><?= $coluna['col_titulo'] ?></div>
            <div id="col_dest_detalhes" class="clear text-right">
                <div><i>Por 'Autor da Coluna'</i></div>
                <div><i>Há 5 min.</i></div>
            </div>
            <div class="text-right">
                <a href="/coluna/<?=$coluna['ctg_apelido']?>/<?=$coluna['col_id']?>" target="_blank">
                    <div class="btn btn-warning" style="min-width: 100px; font-size: 16px; background-color: <?=$cor?>; border-color: <?=$cor?>">Saiba mais...</div>
                </a>
            </div>
        </div>
    </div>
</li>
<script>
    $()
</script>
<?php endif; ?>  


