<?php 
$coluna = $this->coluna;
$categoria = $coluna['ctg_apelido'];

$cor = '#D89D33';
if($categoria == 'pensando-coracao'){
    $cor = '#C270AD';
} else if($categoria == 'pensando-biblia') {
    $cor = '#2D84C6';
}

?>

<style>
    
    .coluna_resumida {
        background: white;
        border-top: 3px solid;
        margin: 15px 15px 0 0px;
        padding: 0px 5px;
        height: 108px;
    }
    
 
</style>

<div class="col-md-9 bloco coluna_resumida" style="border-top-color: <?=$cor?>">
    <div id="col_res_titulo" class="bloco-titulo"><?= $coluna['col_titulo'] ?></div>
    <div id="col_dest_detalhes" class="text-right">
        <div>Por <i><?= $coluna['usr_nome'].' '.$coluna['usr_sobrenome'] ?></i></div>
    </div>
    <div class="text-right" style="position: absolute; bottom: 5px; right: 5px">
        <a href="/coluna/<?=$coluna['ctg_apelido']?>/<?=$coluna['col_id']?>">
            <div class="btn btn-warning" style="min-width: 100px; font-size: 16px; background-color: <?=$cor?>; border-color: <?=$cor?>">Saiba mais...</div>
        </a>
    </div>
</div>
    

