<div id="voltar" class="col-md-1 col-md-push-6 text-center" style="color: #C270AD; cursor: pointer"><i class="fa fa-arrow-circle-left fa-2x"></i></div>
<?php 
if(isset($this->coluna)): 
    $coluna = $this->coluna;
    echo $this->partial('exibe_coluna',['coluna'=>$coluna]);
?>
<?php 
else:
    
?>

exibir colunas da categoria

<?php endif; ?>

<script>
    $(function (){
         $(".navbar .icone-categoria img[data-ctg!='pensando_coracao']").hide();
        $(".navbar .icone-categoria img[data-ctg='pensando_coracao']")
                .attr('src','/img/id-visual/coracao-circle.svg')
                .parent()
                .removeClass('col-md-9')
                .addClass('col-md-pull-1 col-md-11')
                .append('<div style="color: #FDFDFE; font-size:1.2em">Pensando com o Coração<div>');
        $('#container-topo').css({'border-bottom':'1px solid #C270AD'});
        $('#voltar').css('top', $(window).height()/2 ).click(function (){window.location='/'})
    })
</script>