<div id="voltar" class="col-md-1 col-md-push-5 text-center" style="color: #2D84C6; cursor: pointer"><i class="fa fa-arrow-circle-left fa-2x"></i></div>
<?php 
if(isset($this->coluna)): 
    $coluna = $this->coluna;
    echo $this->partial('exibe_coluna',['coluna'=>$coluna]);
?>
<?php 
else:
    
?>

exibir colunas da categoria

<?php endif; ?>

<script>
    $(function (){
         $(".navbar .icone-categoria img[data-ctg!='pensando_biblia']").hide();
        $(".navbar .icone-categoria img[data-ctg='pensando_biblia']")
                .attr('src','/img/id-visual/biblia-circle.svg')
                .parent()
                .removeClass('col-md-9')
                .addClass('col-md-pull-10 col-md-11')
                .append('<div style="color: #FDFDFE; font-size:1.2em">Pensando com a Bíblia<div>');
        $('#container-topo').css({'border-bottom':'1px solid #2D84C6'})
        $('#voltar').css('top', $(window).height()/2 ).click(function (){window.location='/'})
    })
</script>