<style>
    #index-principal > div {
        background: white;
    }
    #index-principal * {
        border: 1px solid;
    }
    .coluna_resumida{
        height: 50px;
    }
    .coluna_detalhes > div{
        margin: 1% 0;
    }
</style>

<div id="index-principal" class="col-xs-30 no-padding">
    <div class="col-xs-30 col-md-9 no-padding" >
        <div class="coluna_detalhes col-xs-13 col-md-30 no-padding" style="margin-top: 5%">
            <div class="col-xs-20" style="height: 200px; margin-left: 14%">imagem</div>
            <div class="col-xs-30" style="height: 50px">titulo destaque</div>
            <div class="col-xs-30" style="height: 35px">info gerais</div>
        </div>
        <div class="col-xs-15 col-md-30 no-padding">
            <div class="col-xs-30 col-md-30 coluna_resumida"><div class="col-xs-25">titulo simulando uma coluna com um titulo bem grande sendo que o autor é fulano de tal</div><div class=" col-xs-offset-26">expandir</div></div>
            <div class="col-xs-30 col-md-30 coluna_resumida"><div class="col-xs-25">titulo simulando uma coluna com um titulo bem grande sendo que o autor é fulano de tal</div><div class=" col-xs-offset-26">expandir</div></div>
            <div class="col-xs-30 col-md-30 coluna_resumida"><div class="col-xs-25">titulo simulando uma coluna com um titulo bem grande sendo que o autor é fulano de tal</div><div class=" col-xs-offset-26">expandir</div></div>
            <div class="col-xs-30 col-md-30 coluna_resumida"><div class="col-xs-25">titulo simulando uma coluna com um titulo bem grande sendo que o autor é fulano de tal</div><div class=" col-xs-offset-26">expandir</div></div>
            <div class="col-xs-30 col-md-30 coluna_resumida"><div class="col-xs-25">titulo simulando uma coluna com um titulo bem grande sendo que o autor é fulano de tal</div><div class=" col-xs-offset-26">expandir</div></div>
            <div class="col-xs-30 col-md-30 coluna_resumida"><div class="col-xs-25">titulo simulando uma coluna com um titulo bem grande sendo que o autor é fulano de tal</div><div class=" col-xs-offset-26">expandir</div></div>
            <div class="col-xs-30 col-md-30 coluna_resumida"><div class="col-xs-25">titulo simulando uma coluna com um titulo bem grande sendo que o autor é fulano de tal</div><div class=" col-xs-offset-26">expandir</div></div>
            <div class="col-xs-30 col-md-30 coluna_resumida"><div class="col-xs-25">titulo simulando uma coluna com um titulo bem grande sendo que o autor é fulano de tal</div><div class=" col-xs-offset-26">expandir</div></div>
        </div>
        <div class="col-xs-2 col-md-30 text-center" style="">
            <div class="col-xs-30 col-md-5 col-md-push-10">+</div>
            <div class="col-xs-30 col-md-5 col-md-push-10">-</div>
        </div>     
    </div>
    
    
</div>

<script>
    
</script>