<style>
    .bloco {
        margin-top: 15px;
    }
    
    .bloco-destaque {
        background: white;
        border-top: 3px solid #D89D33;
        margin-right: 15px;
        padding-left: 0;
    }

    .bloco-titulo {
        font-size: 18px; 
        line-height: 25px;
    }
    
    .icone-categoria{ margin-top: 2px; }
    
    .bjqs-caption{
        font-size: 18px; 
        line-height: 25px;
        text-align: left;
        color: white
    }
    
</style>

    <?php
    $ultimas_colunas = $this->ultimas_colunas; 
    $colunas = $this->colunas;
    ?>
    
<div id="slider" class="bloco bloco-destaque col-md-9">
    <ul class="bjqs">
        <?php
            foreach ($ultimas_colunas as $coluna) {
                echo $this->partial('bloco/destaque',['coluna'=>$coluna]);
            }
        ?>
    </ul>
</div>


    <?php
        foreach ($colunas as $coluna) {
            echo $this->partial('bloco/comum',['coluna'=>$coluna]);
        }
    ?>

<script>
    $('#slider').bjqs({
        height      : 485,
        width       : 620,
        responsive  : true,
        automatic   : true,
        showcontrols: false,
        showmarkers : false,
        animspeed   : 3000, //1000 = 1s
        //ref: http://www.basic-slider.com/
      });
</script>