<?php 
$this->plugin('basePath')->setBasePath('/public/');

$this->headMeta()->setProperty("og:locale", "pt_BR")
                ->setProperty("og:site_name", "Os Pensadores");

echo $this->doctype(); 

?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>Pensadores</title>

        <?php
        echo $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
                ->setCharset('UTF-8');
        ?>

        <?php
        echo $this->headScript()
                ->prependFile($this->basePath() . '/js/global.js')
                ->prependFile($this->basePath() . '/js/pensadores.components.plugin.js')
                ->prependFile($this->basePath() . '/js/pensadores.commons.plugin.js')
                ->prependFile($this->basePath() . '/js/plugin_form.js')
                ->prependFile($this->basePath() . '/vendor/outros/js/filter_input.js')
                ->prependFile($this->basePath() . '/vendor/outros/js/jquery_mask.js')
                ->prependFile($this->basePath() . '/vendor/jquery.slider.master/js/bjqs-1.3.min.js')
                ->prependFile($this->basePath() . '/vendor/jquery-ui/datepicker-pt-BR.js')
                ->prependFile($this->basePath() . '/vendor/bootstrap/3.3.2/js/bootstrap.js')
                ->prependFile($this->basePath() . '/vendor/jquery-ui/1.11.4/jquery-ui.js')
                ->prependFile($this->basePath() . '/vendor/jquery/1.11.2.min.js');
        
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/id-visual/favicon.ico'))
                ->prependStylesheet($this->basePath() . '/css/global-responsive.css')
                ->prependStylesheet($this->basePath() . '/css/global.css')
                ->prependStylesheet($this->basePath() . '/vendor/outros/css/normalize.css')
                ->prependStylesheet($this->basePath() . '/vendor/jquery.slider.master/bjqs.css')
                ->prependStylesheet($this->basePath() . '/vendor/font-awesome/4.3.0/css/font-awesome.min.css')
                ->prependStylesheet($this->basePath() . '/vendor/bootstrap/3.3.2/css/bootstrap.css')
                ->prependStylesheet($this->basePath() . '/vendor/jquery-ui/1.11.4/jquery-ui.css')
        ?>
        
        <!--[if lt IE 9]>
            <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
            <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->
        
    </head>
    <style>
        
        @import url(http://fonts.googleapis.com/css?family=Roboto);
        
        html, body {
            height: 100%
        }
        
        body{
            background: black;
            font-family: Arial, Roboto;
            min-width: 400px;
        }
        
        /*OUTROS ELEMENTOS*/
        #container-topo{
            /*height: 90px;*/
            margin: 0;
            border-bottom: 1px solid #D89D33;
        }
        
        /* BOOTSTRAP */
        .navbar {
            background: none;
            border: none;
            margin: 7px;
        }
        
        .container-fluid {
            /*max-width: 1350px;*/
            height: 725px;
            max-width: 1550px;
            /*min-width: 400px;*/
        }

        .layout-icones-categoria{
            margin-top: 10px;
        }
        
        .layout-icone-logar{
            position: absolute; 
            right: 1%; 
        }
        
        #logar a:link, #logar a:visited, #logar a:hover, #logar a:active{
            color: #D89D33;
        }
        
        #logout a:link, #logout a:visited, #logout a:hover, #logout a:active{
            color: #C270AD;
        }
        
        @media (min-width: 1300px) {
            .layout-icones-categoria{
                margin-top: 18px;
            }
        }
        
        @media (min-width: 1500px) {
            .layout-icones-categoria{
                margin-top: 25px;
            }
        }
        
    </style>
    <body>
        <div id="container-topo">
            <nav class="navbar navbar-inverse">
                <div class="col-xs-20 col-md-6 col-md-offset-2 col-xs-push-4 layout-logo-principal">
                    <a href="/">
                        <img src="<?=$this->basePath() . '/img/id-visual/logo_completa.png'?>" />
                    </a>
                </div>
                <div class="col-md-10 col-md-offset-3 layout-icones-categoria">
                    <div class="col-xs-5 col-md-9 col-xs-offset-7 col-md-offset-1 icone-categoria text-center"><img data-ctg='pensando-cabeca' src="<?=$this->basePath() . '/img/id-visual/mente-circle.svg'?>" /></div>
                    <div class="col-xs-5 col-md-9 icone-categoria text-center"><img data-ctg='pensando-coracao' src="<?=$this->basePath() . '/img/id-visual/coracao-circle.svg'?>" /></div>
                    <div class="col-xs-5 col-md-9 icone-categoria text-center"><img data-ctg='pensando-biblia' src="<?=$this->basePath() . '/img/id-visual/biblia-circle.svg'?>" /></div>
                </div>
                <div class="layout-icone-logar">
                    <?php if ($this->sessao()->isLogged()): ?>
                        <div id="logout" class="text-center" style="color: #C270AD;"><a href="/acesso/logout"><i class="fa fa-sign-out fa-2x"></i></a></div>
                    <?php else: ?>
                        <div id="logar" class="text-center" style="color: #D89D33;"><a href="/acesso/login"><i class="fa fa-sign-in fa-2x"></i></a></div>
                    <?php endif; ?>
                </div>
            </nav>
        </div>
        
        <div class="container-fluid col-xs-offset-1 col-sm-offset-2">
        
            <!--<div class="row" id="container-body">-->
                <?php echo $this->content; ?>
            <!--</div>-->
            
        </div> <!-- /container -->

    </body>
</html>
