<?php 
if($_SERVER['HTTP_HOST']=='ospensadores.com'){
    $this->plugin('basePath')->setBasePath('/public/');
}

echo $this->doctype(); 

?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>Pensadores</title>

        <?php
        echo $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
                ->setCharset('UTF-8');
        ?>

        <?php
        echo $this->headScript()
                ->prependFile($this->basePath() . '/js/global.js')
                ->prependFile($this->basePath() . '/js/pensadores.components.plugin.js')
                ->prependFile($this->basePath() . '/js/pensadores.commons.plugin.js')
                ->prependFile($this->basePath() . '/js/plugin_form.js')
                ->prependFile($this->basePath() . '/vendor/outros/js/filter_input.js')
                ->prependFile($this->basePath() . '/vendor/outros/js/jquery_mask.js')
                ->prependFile($this->basePath() . '/vendor/jquery.slider.master/js/bjqs-1.3.min.js')
                ->prependFile($this->basePath() . '/vendor/jquery-ui/datepicker-pt-BR.js')
                ->prependFile($this->basePath() . '/vendor/bootstrap/3.3.2/js/bootstrap.js')
                ->prependFile($this->basePath() . '/vendor/jquery-ui/1.11.4/jquery-ui.js')
                ->prependFile($this->basePath() . '/vendor/jquery/1.11.2.min.js');
        
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/id-visual/favicon.ico'))
                ->prependStylesheet($this->basePath() . '/css/global.css')
                ->prependStylesheet($this->basePath() . '/vendor/outros/css/normalize.css')
                ->prependStylesheet($this->basePath() . '/vendor/jquery.slider.master/bjqs.css')
                ->prependStylesheet($this->basePath() . '/vendor/font-awesome/4.3.0/css/font-awesome.min.css')
                ->prependStylesheet($this->basePath() . '/vendor/bootstrap/3.3.2/css/bootstrap.css')
                ->prependStylesheet($this->basePath() . '/vendor/jquery-ui/1.11.4/jquery-ui.css')
        ?>
        
        <!--[if lt IE 9]>
            <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
            <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->
        
    </head>
    <style>
        
        @import url(http://fonts.googleapis.com/css?family=Roboto);

        html, body {
            height: 100%
        }
        
        body{
            background: black;
            font-family: Roboto
        }
        
        /*OUTROS ELEMENTOS*/
        #container-topo{
            height: 90px;
            margin: 0;
            border-bottom: 1px solid #D89D33;
        }
        
        /* BOOTSTRAP */
        .navbar {
            background: none;
            border: none;
        }
        
        .container-fluid {
            /*max-width: 1350px;*/
            max-width: 1550px;
            min-width: 550px;
            height: 725px;
        }

        .row {
            margin-left: 15px;
            margin-right: 20px
        }
        
        #login a:link, #login a:visited, #login a:hover, #login a:active{
            color: #D89D33;
        }
        
        #logout a:link, #logout a:visited, #logout a:hover, #logout a:active{
            color: #C270AD;
        }
    </style>
    <body>
        <div class="row" id="container-topo">
            <nav class="navbar navbar-inverse">
                <div class="col-md-6 col-md-offset-2">
                    <a href="/">
                        <img style="width: 97%" src="<?=$this->basePath() . '/img/id-visual/logo_completa.svg'?>" />
                    </a>
                </div>
                <div class="col-md-10 col-md-offset-3" style="margin-top: 15px">
                    <div class="col-md-9 icone-categoria text-center"><img data-ctg='pensando_cabeca' src="<?=$this->basePath() . '/img/id-visual/mente-circle.svg'?>" /></div>
                    <div class="col-md-9 icone-categoria text-center"><img data-ctg='pensando_coracao' src="<?=$this->basePath() . '/img/id-visual/coracao-circle.svg'?>" /></div>
                    <div class="col-md-9 icone-categoria text-center"><img data-ctg='pensando_biblia' src="<?=$this->basePath() . '/img/id-visual/biblia-circle.svg'?>" /></div>
                </div>
                <div class="col-md-1" style="position: absolute; right: 1%; top: 30px">
                    <?php if ($this->sessao()->isLogged()): ?>
                        <div id="logout" class="col-md-9 text-center" style="color: #C270AD;"><a href="/acesso/logout"><i class="fa fa-sign-out fa-2x"></i></a></div>
                    <?php else: ?>
                        <div id="login" class="col-md-9 text-center" style="color: #D89D33;"><a href="/acesso/login"><i class="fa fa-sign-in fa-2x"></i></a></div>
                    <?php endif; ?>
                </div>
            </nav>
        </div>
        
        <div class="container-fluid">
        
            <div class="row" id="container-body">
                <?php echo $this->content; ?>
            </div>
            
        </div> <!-- /container -->

    </body>
</html>
