<?php
$this->plugin('basePath')->setBasePath('/public/');

echo $this->headScript()->prependFile($this->basePath() . '/vendor/jquery-html-box-editor/htmlbox.full.js');
echo $this->headScript()->prependFile($this->basePath() . '/vendor/jquery-html-box-editor/bowser.js');


$colunas = $this->colunas;
$series = $this->series;
$colunas_pais = $this->colunas_pais;

$categorias = $this->categorias;
$usuario = $this->usuario;
?>

<style>
    
    #container_colunas{
        background: #EEE;
        padding: 0;
        font-size: 1.1em;
        height: 96px; 
        margin-top: 20px;
        /*padding: 15px*/
    }
    
    #btn_nova_coluna, #tb_exibe_colunas{
        margin: 0 15px;
    }

    .table { width: 92%; }

    @media (min-width: 992px) {
        .table { width: 97%; }
    }
</style>


<div id="container_colunas" class="col-xs-29" >
    <div role="tabpanel">

        <!-- Nav tabs -->
        <ul class="nav nav-tabs" style="margin-top: 10px">
            <li class="active"><a href="#nova_coluna" aria-controls="home" role="tab" data-toggle="tab"><strong>Nova Coluna</strong></a></li>
            <li><a href="#dicas" aria-controls="profile" role="tab" data-toggle="tab"><strong>Dicas</strong></a></li>
        </ul>

        <!-- Tab panes -->
        <div class="tab-content">
            <div class="tab-pane active" id="nova_coluna">
                <span id="colunista_alerta" style="border-radius: 0; font-size: 0.8em;" class="hide"></span>

                <button type="button" id="btn_nova_coluna" class="btn btn-primary" style=" margin-top: 10px">Nova Coluna...</button>
                <table id="tb_exibe_colunas" class="table table-bordered table-condensed col-xs-29" style="margin-top: 10px; background: white;">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Título</th>
                            <th>Editar</th>
                            <th>Excluir</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($colunas as $coluna): 
                            $class_bg = 'warning';
                            if($coluna['ctg_apelido'] == 'pensando-coracao'){
                                $class_bg = 'danger';
                            } else if($coluna['ctg_apelido'] == 'pensando-biblia') {
                                $class_bg = 'info';
                            }
                        ?>
                        <tr data-col_id="<?= $coluna['col_id']?>" class="<?=$class_bg?>">
                                <td class="text-right"><?= $coluna['col_id'] ?></td>
                                <td><?= $coluna['col_titulo'] ?></td>
                                <td class="text-center"><button type="button" class="btn btn-warning btn-editar"><i class="fa fa-edit"></i></button></td>
                                <td class="text-center"><button type="button" class="btn btn-danger btn-excluir"><i class="fa fa-times"></i></button></td>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>


                <!-- Modal -->
                <div class="modal fade" id="modal_colunas" aria-hidden="true">
                    <div class="modal-dialog modal-lg">
                        <div class="modal-content">
                            <div class="modal-header">
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span class="btn btn-danger"><i class="fa fa-times"></i></span></button>
                                <h4 class="modal-title" style="font-weight: bold">Nova coluna...</h4>
                            </div>
                            <div class="modal-body">

                                <form class="form-horizontal">
                                    <div class="form-group" style="margin-bottom: 0">
                                        <label class="col-md-2" style="margin-right: 5px">Colunista: </label>
                                        <div class="col-md-22"> <?= $usuario['usr_nome'].' '.$usuario['usr_sobrenome'].' ('.$usuario['usr_login'].')' ?></div>
                                    </div>
                                    <div class="form-group">
                                        <label class="col-md-1" style="margin-right: 5px">Data:</label>
                                        <div class="col-md-22"> <?= date('d/m/Y H:m') ?></div>
                                    </div>
                                </form>

                                <form id="form_coluna" action="#" method="POST" enctype="multipart/form-data">
                                    <div class="form-group col-md-20">
                                        <label>Título*</label>
                                        <input type="text" name="col_titulo" class="form-control" placeholder="Título" data-obrigatorio />
                                    </div>
                                    
                                    <div class="clear form-group col-md-10">
                                        <label>Categoria*</label>
                                        <select name="ctg_id" class="form-control"  data-obrigatorio>
                                            <option value="0">Selecione...</option>
                                            <?php foreach ($categorias as $categoria) : ?>
                                                <option value="<?= $categoria['ctg_id'] ?>"><?= $categoria['ctg_nome'] ?></option>
                                            <?php endforeach; ?>
                                        </select>

                                    </div>
                                    
                                    <div class=" form-group col-md-10">
                                        <label>Série</label>
                                        <select name="col_pai_id" id="series" class="form-control">
                                            <option value="0">Selecione a coluna pai</option>
                                            <?php foreach ($series as $serie) : ?>
                                                <option value="<?= $serie['col_id'] ?>"><?= $serie['col_titulo'] ?></option>
                                            <?php endforeach; ?>
                                        </select>
                                    </div>
                                    
                                    <div class="form-group col-md-24" id="dv_carregar_imagem">
                                        <div class="col-md-30">
                                            <label>Imagem <sup>(Cuidado: Quanto maior a imagem, maior o tempo para verificar)</sup></label></label>
                                        </div>
                                        <!--<input type="file" name="col_imagem" class="form-control" placeholder="Imagem"  />-->
                                        <div class="col-md-26">
                                            <input type="text" id="col_end_imagem" name="col_end_imagem" class="form-control" placeholder="Endereço da imagem" />
                                        </div>
                                            
                                        
                                        <div class="col-md-1 hide" style="margin-top: 4px" id="dv_imagem_carregando">
                                            <i class="fa fa-spinner fa-pulse"></i>
                                        </div>
                                        <div id="dv_msg_carregamento_imagem" class="col-md-3" style="margin-top: 4px"></div>
                                    </div>
                                    
                                    <div class="form-group col-md-24" id="dv_carregar_imagem">
                                        <div class="col-md-30">
                                            <label>Podcast <sup>(Iframe dado pelo SoundCloud)</sup></label></label>
                                        </div>
                                        <div class="col-md-26">
                                            <input type="text" id="col_podcast" name="col_podcast" class="form-control" placeholder="Endereço do podcast" />
                                        </div>
                                    </div>
                                    
                                    <div class="form-group col-md-30">
                                        <label>Texto* 
                                            <!--<sup>(antes de escrever a coluna, clique no primeiro ícone (parágrafo) para melhorar a formatação da coluna)</sup></label>-->
                                        <textarea id="col_texto" name="col_texto" class="form-control" rows="25" placeholder="Texto" style="width: 858px; height: 550px" data-obrigatorio></textarea>
                                    </div>
                                    <div class="form-group col-md-15">
                                        <label>Resumo</label>
                                        <textarea name="col_resumo" class="form-control" rows="5" placeholder="Resumo"></textarea>
                                    </div>
                                    <div class="form-group col-md-15">
                                        <label>Observação:</label>
                                        <textarea name="col_observacao" class="form-control" rows="5" placeholder="Observação"></textarea>
                                    </div>
                                    <input type="hidden" name="col_id" />
                                </form>
                            </div>
                            <div class="clear modal-footer">
                                <button type="button" id="btn_enviar_coluna" class="btn btn-primary" disabled>Confirmar</button>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
            <div class="tab-pane" id="dicas">
                <div class="text-center clear">
                    <h3>Imagens para divulgação/postagem:</h3>
                    <div class="col-md-offset-0  text-left">
                        <ul>
                            <li>Dica para postagens rápidas (windows): baixe as imagens, acesse o site "http://bannerfans.com/banner_maker.php" (em breve, tutorial) , faça o upload da imagem coloque o texto desejado, personalize, salve ou compartilhe a imagem.</li>
                            <li>Dica para postagens rápidas (celular): baixe as imagens, no aplicativo "No Crop" , faça o upload da imagem, coloque o texto desejado, personalize se quiser, salve ou compartilhe a imagem.</li>
                            <li>Obs 1: Ao priorizar essas imagens você estará divulgando junto com o conteúdo da postagem: A logo, a identidade visual, a categoria da postagem e as 3 principais fontes de informação que temos (site, facebook e instagram)</li>
                            <li>Obs 2: As imagens estão pequenas apenas na exibição do site, pode usar que quando salvar, serão salvas no tamanho original de 768x768 (bem grande rs)</li>
                        </ul>
                    </div>
                    <div class="col-md-offset-2">
                        <img class="col-xs-15 col-md-7" src="<?=$this->basePath()?>/img/divulgacao/post-inst-redes.png" />
                        <img class="col-xs-15 col-md-7" src="<?=$this->basePath()?>/img/divulgacao/post-inst-cab-1.png" />
                        <img class="col-xs-15 col-md-7" src="<?=$this->basePath()?>/img/divulgacao/post-inst-cor-1.png" />
                        <img class="col-xs-15 col-md-7" src="<?=$this->basePath()?>/img/divulgacao/post-inst-bib-1.png" />
                    </div>
                </div>
            </div>
        </div>

    </div>

</div>


<script>
    
    var colunas = <?= (sizeof($colunas)) ?  json_encode($colunas) : "[]" ?> 
    var colunas_pais = <?= (sizeof($colunas_pais)) ?  json_encode($colunas_pais) : "[]" ?> 
   
    var col_id = 0;
    var col_titulo = "";
    var col_texto = "";
    var col_texto_puro = "";
    var ctg_id = "";
    var col_pai_remover = 0;
    var Editor;
    
    
    var eventoEditarClick = function (){
        col_id = $(this).parents('tr').attr('data-col_id');
        var col_dados = buscaColuna(col_id);
        preencheModalColunas(col_dados);
        verificaCamposObrigatorios();
        ativaSalvar();
        abreModalColunas();
    }
    
    var eventoExcluirClick = function (botao){
        $().confirmar({
            text: 'Tem certeza que deseja excluir esta coluna?',
            yes: function (){
                col_id = $(botao.target).parents('tr').attr('data-col_id');
                $.ajax({
                    url:'/coluna/admin/excluir',
                    data:{col_id:col_id}
                }).done(function (result){
                    if( ! result[0]){
                        $($('#colunista_alerta')).showMessageTarge({
                            message: 'Ocorreu algum erro ao excluir a coluna, verifique!',
                            type: 'danger'
                        });
                    }
                    
                    $('#tb_exibe_colunas tr[data-col_id='+col_id+']').remove();
                    col_id = 0;
                    
                    $($('#colunista_alerta')).showMessageTarge({
                        message: 'Coluna excluída com sucesso!',
                        type: 'success'
                    });
                    atualizaTamanhoContainerColunas()
                });
            },
            no: function (){
                $($('#colunista_alerta')).showMessageTarge({
                    message: 'Ação cancelada, nada foi alterado.',
                    type: 'warning'
                });
            }
        });
    }
    
    function preencheModalColunas(col_dados){
        $('input:file').val('');
        $.each(col_dados, function (key, dados){
            
            dados = (key === 'col_pai_id' && (dados==null || dados==false))?0:dados;
            $('#form_coluna [name='+key+']').val(dados);
            col_texto = $('#col_texto').val();
        });
        
        Editor.set_text($('#col_texto').val().replace(/(?:\r\n|\r|\n)/g, '<br />'));
//        Editor.set_text('dasdfasdf');
        
        col_id = col_dados.col_id;
        $('#modal_colunas .modal-title').html(col_dados.col_titulo);
        
        //oculta da lista de colunas para serie, a coluna selecionada
        $('#series option[value='+col_id+']').hide();
        $('#series :not(option[value='+col_id+'])').show();
        col_pai_remover = $('#series').val();
        
        if( colunas_pais.indexOf(col_dados.col_id)>-1 ){
            $('#series').prop('disabled',true);
            $('#series option:first').html('Está coluna já é uma série.');
        } else {
            $('#series').prop('disabled',false);
            $('#series option:first').html('Selecione a coluna pai');
        }
    }
    
    function buscaColuna(col_id){
        $.each(colunas, function (key, coluna){
            if(coluna.col_id == col_id){
                col_dados = coluna;
                return false;
            }
        });
        return col_dados;
    }
    
    function limpaFormColuna(){
        $('#modal_colunas .modal-title').html('Nova coluna...');
        $('#form_coluna').find('textarea, input:text, input:hidden, input:file').val('');
        Editor.set_text('')
        $('#form_coluna').find('select').val(0);
        $('#series').prop('disabled',false);
        $('#series option:first').html('Selecione a coluna pai');
    }
    
    function verificaCamposObrigatorios(){
        $('#form_coluna').find('textarea, [type=text]').keyup();
        $('#form_coluna').find('select').change();
    }
    
    function abreModalColunas(){
        $('#modal_colunas').modal({
            backdrop: 'static',
            keyboard: false
        });
    }
    
    function getCorFundoTr(ctg_id){
        cor_fundo = 'warning';
        if(ctg_id == 2){
            cor_fundo = 'danger';
        } else if(ctg_id == 3){
            cor_fundo = 'info';
        }
        return cor_fundo;
    }
    
    function ativaSalvar(){
        
        if(col_titulo && ctg_id>0){
            $('#btn_enviar_coluna').prop('disabled',false) 
        } else {
            $('#btn_enviar_coluna').prop('disabled',true) ;
        }
    }
    
    function atualizaTamanhoContainerColunas(){
            var qtd_colunas = $('#tb_exibe_colunas tbody tr').length;
            var novo_tamanho = 60+0+ (qtd_colunas * 45);
//            var novo_tamanho = 500;
            $('#container_colunas').css('height',novo_tamanho)
        }
    
    function iniciaEditor(){
        Editor = $("#col_texto")
                                .addClass('col-lg-30')
                                .htmlbox({
                                    toolbars:[
                                            ["separator","bold","italic","underline","separator","quote","outdent", "separator","left","center","right","justify","separator","ol","ul","separator","link","unlink","separator","hr","separator","undo","redo"]
                                        ],
                                        css:"body{font-family:verdana;font-size:11px;}",
                                        icons:"silk",
                                        skin:"blue",
                                        keyup: function (){
                                            console.log(':)');
                                        }
                                })
        
        
        $("table#col_texto_wrap table tbody td[class$=button]:not(:last)").click(function (){
            col_texto = Editor.get_html();
            col_texto_puro = Editor.get_text().startContainer.innerText;
            $('#col_texto').val(col_texto); 
            ativaSalvar();
        });
        
        var editor = $('iframe').contents().find('body');
        $(editor).keyup(function (){ 
            col_texto = Editor.get_html();
            col_texto_puro = Editor.get_text().startContainer.innerText;
            $('#col_texto').val(col_texto); 
//            ativaSalvar();         
        });

    }
    
    $(function (){
        atualizaTamanhoContainerColunas();
        
        $('#btn_nova_coluna').click(function (){
            col_id = 0;
            limpaFormColuna();
            verificaCamposObrigatorios();
            ativaSalvar();
            abreModalColunas();
        });
    
        $('.btn-editar').click(eventoEditarClick);

        $('.btn-excluir').click(eventoExcluirClick);

        $('#form_coluna input[name=col_titulo]').keyup(function (e){
            col_titulo = $(this).val();
            ativaSalvar();
        });

        $('#form_coluna select[name=ctg_id]').change(function (){
            ctg_id = $(this).val()
            ativaSalvar();
        });
        
        $('#btn_enviar_coluna').click(function (){$('#form_coluna').submit()})
        
        $('#col_end_imagem').focusout(function (){
            $.ajax({
                url:'/coluna/admin/pegarImagemPorUrl',
                data:{url:this.value},
                beforeSend: function (){ $('#dv_msg_carregamento_imagem').hide(); $('#dv_imagem_carregando').removeClass('hide');},
                complete: function (){ $('#dv_imagem_carregando').addClass('hide');}
            }).done(function (result){
                $('#dv_msg_carregamento_imagem').html('').append('<i class="fa fa-check-circle"></i> Ok').show();
            }).fail(function (error){
                $('#dv_msg_carregamento_imagem').html('').append('<i class="fa fa-times-circle"></i> Erro').show();
            })
        });
        
        $('#form_coluna').submit(function (){
            $('input[name=col_id]').val(col_id);
            $('#series').prop('disabled',false);
            $('#col_texto').val($('iframe').contents().find('body').html());
            var formData = new FormData(this);
            $.ajax({
                url:'/coluna/admin/save',
                data:formData,
                cache:false,
                contentType: false,
                processData: false,
            }).done(function (result){
                
                coluna = result.coluna;
                serie = result.serie;
                imagem = result.imagem;
                
                if( ! coluna.hasOwnProperty('col_id')){
                    $().alerta("Ocorreu algum problema ao postar a coluna, verifique.");
                }

                $('#modal_colunas').modal('hide');

                
                if(serie.hasOwnProperty('ser_id')){
                    if( ! serie.hasOwnProperty('ignorar_serie')){
                        // inseriu series
                        colunas_pais.push(serie.col_id.toString());
                        
                    }
                } else {
                    var index = colunas_pais.indexOf(col_pai_remover);
                    if (index >= 0) {
                        colunas_pais.splice( index, 1 );
                    }
//                    serie = {
//                            serie_id : serie.serie_id,
//                            col_pai_id : serie.col_id,
//                            col_id: serie.col_filho_id,
//                            ser_ordem : serie.ser_ordem
//                        };
                }
                
                serie_alterada = {
                        ser_id : serie.ser_id,
                        col_pai_id : serie.col_id,
                        ser_ordem : serie.ser_ordem
                    };
                
                //atualiza a coluna na tabela com os novos campos
                $(colunas).each(function (i, cada_coluna){    
                    if(cada_coluna.col_id === col_id){
                        for(campo in coluna){ colunas[i][campo] = coluna[campo]; }
                        
                        if(serie.serie_id!==null){
                            for(campo in serie_alterada) { colunas[i][campo] = serie_alterada[campo]; }
                        }
                        
                        console.log(colunas);
                        return false;
                    }
                    
                });

                var acao = '';
                if(col_id){
                    acao = 'alterada';
                    
                    $('#tb_exibe_colunas tr[data-col_id='+coluna.col_id+'] td:nth-child(2)').html(coluna.col_titulo);
                    $('#tb_exibe_colunas tr[data-col_id='+coluna.col_id+']').attr('class', getCorFundoTr(coluna.ctg_id));

                } else {
                    acao = 'inserida';
                    
                    colunas.push(coluna);
                    
                    $('#tb_exibe_colunas tbody').prepend('\
                                                <tr data-col_id="'+coluna.col_id+'" class="'+getCorFundoTr(coluna.ctg_id)+'">\
                                                    <td class="text-right">'+coluna.col_id+'</td>\
                                                    <td>'+coluna.col_titulo+'</td>\
                                                    <td class="text-center"><button type="button" class="btn btn-warning btn-editar"><i class="fa fa-edit"></i></button></td>\
                                                    <td class="text-center"><button type="button" class="btn btn-danger btn-excluir"><i class="fa fa-times"></i></button></td>\
                                                </tr>');

                    $('#tb_exibe_colunas').find('tbody tr:first button.btn-editar').click(eventoEditarClick)
                    $('#tb_exibe_colunas').find('tbody tr:first button.btn-excluir').click(eventoExcluirClick)
                }

                var message = 'Coluna '+ acao +' com sucesso!';
                var type = 'success';

                if(typeof imagem != 'undefined' && ! imagem.hasOwnProperty('caminho')){
                    message = 'Coluna '+ acao +' com sucesso, mas ocorreu algum problema com a imagem.';
                    type = 'warning';
                }

                $($('#colunista_alerta')).showMessageTarge({
                    message: message,
                    type: type
                });

                atualizaTamanhoContainerColunas()

            });
            return false;
        });
        
        iniciaEditor();
        
    });
</script>
